config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'reviews/new'
  get '/about', to: 'pages#about'
  get '/crisis', to: 'pages#crisis'

  root "apartments#index"
  resources :apartments, except: [:index] do
    resources :reviews, only: [:new, :create]
    resources :visits, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
  resources :visits, only: [:destroy]
  resources :posts, only: [:index, :show, :new, :create, :destroy]
  resources :articles, only: [:index]
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :visits
  has_one_attached :photo
  belongs_to :user

  validates :name, :address, :description, presence: true
  validates :name, uniqueness: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :link, :source, :extract, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :apartment

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many  :posts, dependent: :destroy
  has_many  :apartments, dependent: :destroy
  has_many :appointmets
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :user
  belongs_to :apartment

  validates :date, presence: true
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @apartments = Apartment.all
    @markers = @apartments.geocoded.map do |apartment|
      {
        lat: apartment.latitude,
        lng: apartment.longitude
      }
    end
  end

  def show
    @apartment = set_apartment
    @markers = [{
      lat: @apartment.latitude,
      lng: @apartment.longitude,
    }]
  end

  def new
    @apartment = Apartment.new
    # @apartment.user_id = current_user.id
  end

  def create
    @apartment = Apartment.new(apartment_params)
    if @apartment.save
      redirect_to apartment_path(@apartment), notice: 'Apartment was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @apartment = set_apartment
  end

  def update
    @apartment = set_apartment
    @apartment.update(apartment_params)
    redirect_to apartment_path(@apartment), notice: 'Apartment was successfully updated.'
  end

  def destroy
    @apartment = set_apartment
    @apartment.destroy
    redirect_to root_path, notice: 'Apartment was successfully destroyed.'
  end

  private

  def apartment_params
    params.require(:apartment).permit(:name, :address, :price, :square_meters, :description, :photo)
  end

  def set_apartment
    @apartment = Apartment.find(params[:id])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  
  def index
    @articles = Article.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:about, :crisis]

  def about
  end

  def crisis
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @posts = Post.all
  end

  def show
    @post = set_post
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to posts_path, notice: "Post was successfully created"
    else
      render :new
    end
  end

  def destroy
    @post = set_post
    @post.destroy
    redirect_to posts_path, notice: "Post was successfully deleted"
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :photo)
  end

  def set_post
    Post.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_apartment, only: [:new, :create]

  def new
    @apartment = set_apartment
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.apartment = set_apartment
    if @review.save
      redirect_to apartment_path(@apartment), notice: 'Review was successfully created.'
    else
      render :new, status: :unprocessable_entity, notice: 'Review could not be created.'
    end
  end

  def destroy
    @review= Review.find(params[:id])
    @review.destroy
    redirect_to apartment_path(@review.apartment), status: :see_other, notice: 'Review was successfully destroyed.'
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end

  def set_apartment
    @apartment = Apartment.find(params[:apartment_id])
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_apartment, only: [:new, :create]

  def new
    @apartment = set_apartment
    @visit = Visit.new
  end

  def create
    @visit = Visit.new(visit_params)
    @visit.apartment = set_apartment
    @visit.user = current_user
    if @visit.save
      redirect_to apartment_path(@apartment), notice: 'You can now visit this glorious heaven.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy
    redirect_to apartment_path(@visit.apartment), status: :see_other, notice: 'Booking was successfully destroyed.'
  end

  private

  def visit_params
    params.require(:visit).permit(:date)
  end

  def set_apartment
    @apartment = Apartment.find(params[:apartment_id])
  end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Havens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container-70">
  <h1>Who are we?</h1>
  <p>
    Hey there!
    <br><br>
    We set out to build an Airbnb clone using Ruby on Rails. Our mission? To master the ins and outs of web development—think creating, reading, updating, and deleting stuff, making new pathways, writing reviews, plotting things on maps, and playing around with posting.
    <br><br>
    While brainstorming about a platform for finding a sweet spot to crash, we couldn't shake off a big issue: finding a decent place to live in the city without breaking the bank. That got us thinking—why not chat about housing in a not-so-serious way?
    <br><br>
    Finding a home sweet home on an average wage in the city is no walk in the park. That's where we step in. This platform is now just about our coding adventures; but it would be cool if in the future it'd become a spot to chat about the real struggles of finding a place to call your own in the urban jungle.
    <br><br>
    Stick around and hopefully in the near future we'll dive into these topics, swap stories, and maybe—just maybe—add a drop to the bucket of conversations about snagging a spot in the city. Welcome to our corner, where we're not just about places to stay but also about chatting, exploring, and understanding the ever-changing vibe of city living.
  </p>
</div>

app/views/pages/crisis.html.erb
<div class="container-70">
  <h1>The housing crisis</h1>
  <p>“The world is grappling with a situation where more and more people are unable to afford their housing costs. Millions lack the financial means to access safe, secure and habitable housing,” said Balakrishnan Rajagopal, the UN Special Rapporteur on the right to adequate housing.</p>
  <a href="https://www.ohchr.org/en/press-releases/2023/10/un-expert-urges-action-end-global-affordable-housing-crisis">UN expert urges action to end global affordable housing crisis</a>
  <br><br><br>
  <p>In australia house prices have risen for the past three months. In America a widely watched index of housing values has risen by 1.6% from its low in January, and housebuilders’ share prices have done twice as well as the overall stockmarket. In the euro area the property market looks steady. “[M]ost of the drag from housing on gdp growth from now on should be marginal,” wrote analysts at jpmorgan Chase, a bank, in a recent report about America. “[W]e believe the peak negative drag from the recent housing-market slump to private consumption is likely behind us,” wrote wonks at Goldman Sachs, another bank, about South Korea.</p>
  <a href="https://www.economist.com/finance-and-economics/2023/06/12/is-the-global-housing-slump-over">Is the global housing slump over?</a>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  © from parrot to panda 2023
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= link_to "Havens", root_path, class: "logo" %>
  <div class="buttons-box">
    <a href="<%= articles_path %>" title="Housing crisis"><i class="fa-solid fa-house-chimney-crack fa-lg"></i></a>
    <a href="<%= about_path %>" title="About us"><i class="fa-solid fa-circle-info fa-lg"></i></a>
    <% if user_signed_in? %>
      <a href="<%= new_post_path %>" title="Add a post"><i class="fa-solid fa-square-plus fa-lg"></i></a>
      <a href="<%= posts_path %>" title="Posts"><i class="fa-solid fa-comment fa-lg"></i></a>
      <a href="<%= edit_user_registration_path %>" title="Edit profile"><i class="fa-solid fa-house-user fa-lg"></i></a>
      <a href="<%= destroy_user_session_path %>" data-turbo-method="delete" title="Log out"><i class="fa-solid fa-right-from-bracket fa-lg"></i></a>
    <% else %>
      <%= link_to "Log in", new_user_session_path, class: "btn-nav" %>
      <%= link_to "Sign up", new_user_registration_path, class: "btn-nav" %>
    <% end %>
  </div>
</div>