config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'reviews/new'
  get '/about', to: 'pages#about'
  get '/crisis', to: 'pages#crisis'

  root "apartments#index"
  resources :apartments, except: [:index] do
    resources :reviews, only: [:new, :create]
    resources :visits, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
  resources :visits, only: [:destroy]
  resources :posts, only: [:index, :show, :new, :create, :destroy]
  resources :articles, only: [:index]
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :visits
  has_one_attached :photo
  belongs_to :user

  validates :name, :address, :description, presence: true
  validates :name, uniqueness: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :link, :source, :extract, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :apartment

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many  :posts, dependent: :destroy
  has_many  :apartments, dependent: :destroy
  has_many :appointmets
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :user
  belongs_to :apartment

  validates :date, presence: true
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @apartments = Apartment.all
    @markers = @apartments.geocoded.map do |apartment|
      {
        lat: apartment.latitude,
        lng: apartment.longitude
      }
    end
  end

  def show
    @apartment = set_apartment
    @markers = [{
      lat: @apartment.latitude,
      lng: @apartment.longitude,
    }]
  end

  def new
    @apartment = Apartment.new
    # @apartment.user_id = current_user.id
  end

  def create
    @apartment = Apartment.new(apartment_params)
    if @apartment.save
      redirect_to apartment_path(@apartment), notice: 'Apartment was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @apartment = set_apartment
  end

  def update
    @apartment = set_apartment
    @apartment.update(apartment_params)
    redirect_to apartment_path(@apartment), notice: 'Apartment was successfully updated.'
  end

  def destroy
    @apartment = set_apartment
    @apartment.destroy
    redirect_to root_path, notice: 'Apartment was successfully destroyed.'
  end

  private

  def apartment_params
    params.require(:apartment).permit(:name, :address, :price, :square_meters, :description, :photo)
  end

  def set_apartment
    @apartment = Apartment.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user! 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  
  def index
    @articles = Article.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:about, :crisis]

  def about
  end

  def crisis
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @posts = Post.all
  end

  def show
    @post = set_post
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to posts_path, notice: "Post was successfully created"
    else
      render :new
    end
  end

  def destroy
    @post = set_post
    @post.destroy
    redirect_to posts_path, notice: "Post was successfully deleted"
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :photo)
  end

  def set_post
    Post.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_apartment, only: [:new, :create]

  def new
    @apartment = set_apartment
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.apartment = set_apartment
    if @review.save
      redirect_to apartment_path(@apartment), notice: 'Review was successfully created.'
    else
      render :new, status: :unprocessable_entity, notice: 'Review could not be created.'
    end
  end

  def destroy
    @review= Review.find(params[:id])
    @review.destroy
    redirect_to apartment_path(@review.apartment), status: :see_other, notice: 'Review was successfully destroyed.'
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end

  def set_apartment
    @apartment = Apartment.find(params[:apartment_id])
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_apartment, only: [:new, :create]

  def new
    @apartment = set_apartment
    @visit = Visit.new
  end

  def create
    @visit = Visit.new(visit_params)
    @visit.apartment = set_apartment
    @visit.user = current_user
    if @visit.save
      redirect_to apartment_path(@apartment), notice: 'You can now visit this glorious heaven.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy
    redirect_to apartment_path(@visit.apartment), status: :see_other, notice: 'Booking was successfully destroyed.'
  end

  private

  def visit_params
    params.require(:visit).permit(:date)
  end

  def set_apartment
    @apartment = Apartment.find(params[:apartment_id])
  end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/apartments/edit.html.erb
<div class="container-50">
  <h2>Edit <%= @apartment.name %></h2>
  <%= simple_form_for [@apartment] do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :price %>
    <%= f.input :square_meters %>
    <%= f.input :description %>
    <%= f.submit "Update haven", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/apartments/index.html.erb
<div class="<%= "banner-img#{rand(1..4)}" %> banner">
  <div class="black-veil"></div>
  <div class="banner-text">
    <h1>Discover<br>
    the future<br>
    of housing</h1>
    <p>Your gate to becoming a homeowner on a budget!</p>
  </div>
</div>
<div class="container-100" id="index-list">
  <div class="grid">
    <% @apartments.each do |apartment| %>
      <div class="card">
        <%= link_to apartment_path(apartment) do %>
          <%= cl_image_tag apartment.photo.key %>
          <div class="text">
            <h3><%= apartment.name %></h3>
            <p>
              <%= apartment.address %><br>
              <em><%= apartment.description.truncate(30) %></em>
            </p>
            <div class="numbers">
              <p><%= apartment.square_meters %> m2</p>
              <p><%= apartment.price %>k €</p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/apartments/new.html.erb
<div class="container-50">
  <h2>Add a haven</h2>
  <%= simple_form_for [@apartment] do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :price %>
    <%= f.input :square_meters %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <div class="centered">
      <%= f.submit "Create haven", class: "btn btn-primary mt-3" %>
    </div>
  <% end %>
</div>

app/views/apartments/show.html.erb
<div class="container-100">
  <div class="flex">
    <div class="left">
      <h2><%= @apartment.name %></h2>
      <p>Address: <%= @apartment.address %></p>
      <p><%= @apartment.description %></p>
      <br><br>
      <p>Price: <%= @apartment.price %>k €</p>
      <p>Dimensions: <%= @apartment.square_meters %> m2</p>
      <br><br>
      <div>
        <h3>Book a visit</h3>
        <p>Come and witness this amazing paradise! Because nothing says 'worth your money' like seeing it with your own eyes.</p>
        <%= link_to "Make a booking", new_apartment_visit_path(@apartment) %>
        <br><br>
        <% @apartment.visits.each do |visit| %>
          <% if visit.user == current_user %>
            <div style="display:flex; gap: 20px;">
              <strong><p>You'll visit this majestic heaven on <%= "#{(visit.date.strftime('%d %B, %Y'))}" %> at <%= "#{(visit.date.strftime('%H : %M'))}" %></p></strong>
              <a href="<%= visit_path(visit) %>" data-turbo-method="delete" data-turbo-confirm="Are you sure?" class="bin"><i class="fa-regular fa-trash-can"></i></a>
            </div>
          <% end %>
        <% end %>
        <br><br>
      </div>
      <div class="flex-next">
        <h3>Reviews</h3>
        <a href="<%= new_apartment_review_path(@apartment) %>"><i class="fa-solid fa-plus"></i></a>
      </div>
      <ul class="review">
        <% if @apartment.reviews.empty? %>
          <li>No reviews yet</li>
        <% else %>
          <% @apartment.reviews.each do |review| %>
            <div class="review-card">
              <li><%= review.content%></li>
              <a href="<%= review_path(review) %>" data-turbo-method="delete" data-turbo-confirm="Are you sure?" class="delete"><i class="fa-regular fa-trash-can"></i></a>
            </div>
          <% end %>
        <% end %>
      </ul>
      <% if current_user == @apartment.user %>
        <div class="show-buttons">
          <%= link_to "Edit this haven", edit_apartment_path(@apartment), class: "button green", style: "margin-right:10px;" %>
          <%= link_to "Delete this haven",
            apartment_path(@apartment),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "button red" %>
        </div>
      <% end %>
    </div>
    <div class="right">
      <div>
        <%= cl_image_tag @apartment.photo.key %>
      </div>
      <div class="map-container"
        data-controller="map"
        id="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container-70">
  <h1>The housing crisis</h1>
  <% @articles.each do |article| %>
    <p>"<%= "#{article.extract}" %>"</p>
    <a href="<%= article.link %>"><%= article.title %></a>
    <br><br>
    <p><%= article.date.strftime("%d %B %Y") %></p>
    <br><br>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="container-50">
  <h2>Edit <%= @post.name %></h2>
  <%= simple_form_for [@post] do |f| %>
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.submit "Update post", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="container-70">
  <h1>Sharing interesting facts on housing</h1>
  <h3>How much do flats cost in your area?</h3>
  <div class="mt-4">
    <% @posts.each do |post|%>
    <div class="post">
      <div class="post-card">
        <h4><%= post.title %></h4>
        <p><%= post.content %></p>
        <p><%= post.user.email %></p>
        <p><%= post.created_at.strftime("%d/%m/%Y") %></p>
        <% if post.user == current_user %>
          <%= link_to "Delete", post_path(post), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        <% end %>
      </div>
      <div>
        <% if post.photo.attached? %>
          <%= cl_image_tag post.photo.key, class: "post-image" %>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container-50">
  <h2>Add a post</h2>
  <%= simple_form_for [@post] do |f| %>
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :photo, as: :file %>
    <div class="centered">
      <%= f.submit "Create post", class: "btn btn-primary mt-3" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container-50">
  <h2><%= @post.title %></h2>
  <p><%= @post.content %></p>
  <p><%= @post.created_at.strftime("%d/%m/%Y") %></p>
  <p><%= @post.user.email %></p>
</div>

app/views/reviews/new.html.erb
<div class="container-50">
  <h2>Add a review for <%= @apartment.name %></h2>
  <%= simple_form_for [@apartment, @review] do |f|%>
    <%= f.input :content%>
    <%= f.submit "Submit review", class: "btn btn-primary"%>
  <%end%>
</div>

app/views/visits/new.html.erb
<div class="container-50">
  <h2>Book a visit for <%= @apartment.name %></h2>
  <%= simple_form_for [@apartment, @visit] do |f|%>
    <%= f.input :date%>
    <%= f.submit "Confirm visit", class: "btn btn-primary"%>
  <%end%>
</div>